version: "3.8"

services:
  backend:
    build:
      context: ./7server
      dockerfile: Dockerfile
    container_name: card-back
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3069:3069"
    restart: unless-stopped

  frontend:
    build:
      context: ./7game
      dockerfile: Dockerfile
      args:
        VITE_FRONT_SOCKET_IP: "49.13.58.73:3069"
    container_name: card-front
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "80:8081"
    depends_on:
      - backend
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30 
      - WATCHTOWER_LABEL_ENABLE=true
