version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: card-back
    ports:
      - "3069:3069"
    restart: unless-stopped

  frontend:
    build:
      context: ./7game
      dockerfile: Dockerfile
      args:
        VITE_FRONT_SOCKET_IP: "49.13.58.73:3069"
    container_name: card-front
    ports:
      - "80:8081"
    depends_on:
      - backend
    restart: unless-stopped
