services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: card-back
    ports:
      - "443:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_FRONT_SOCKET_IP: "91.99.223.75:443"
    container_name: card-front
    ports:
      - "80:8081"
    depends_on:
      - backend
    restart: unless-stopped
